### ISSUE TITLE
Simple test for gazebo

### ISSUE THREAD

**Issue by miguelriemoliveira** [Kazadhum/ribot#1]

**Comment by miguelriemoliveira** [comment]
Great that you are moving forward!

**Comment by Kazadhum** [comment]
Hi! It seems that the GitHub closed the issue automatically once I merged the branches... I'm now writing the subscriber publisher and will close this issue again once that's done!

**Comment by Kazadhum** [comment]
Hi @miguelriemoliveira!

This was concluded just now. I'll close this issue. The next step is to reconfigure the calibration package to reflect the new changes and create a dataset. I'll make a new issue for that.

Thank you for the help yesterday!
