### ISSUE TITLE
Calibration Package Reconfiguration and dataset creation

### ISSUE THREAD

**Issue by Kazadhum** [Kazadhum/ribot#2]
The next step to setting this system up is to reconfigure its ATOM calibration package and create a new dataset with the data properly stored.

**Comment by Kazadhum** [comment]
A bagfile was recorded and the calibration package was configurated!
Here's the fixed calibration tree @miguelriemoliveira:

![image](https://github.com/user-attachments/assets/dde204cc-916e-4b0f-a82b-f2f58339e4a0)

Now to record a dataset...

**Comment by Kazadhum** [comment]
Finished recording a dataset! Now back to testing the Liang calibration method...

Closing issue...

**Comment by miguelriemoliveira** [comment]
> A bagfile was recorded and the calibration package was configurated! Here's the fixed calibration tree @miguelriemoliveira:

Looks good.
